import { Product, Category, Coupon } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-dinnerware',
    name: 'Dinnerware',
    slug: 'dinnerware',
    image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=600&q=80',
    description: 'Artisanal ceramic plates, dinner sets & bowls designed to elevate dining',
    itemCount: 45,
  },
  {
    id: 'cat-serveware',
    name: 'Serveware',
    slug: 'serveware',
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=600&q=80',
    description: 'Handcrafted trays, platters, salad bowls & serving boards',
    itemCount: 28,
  },
  {
    id: 'cat-drinkware',
    name: 'Drinkware',
    slug: 'drinkware',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    description: 'Amber glass tumblers, textured highballs, ribbed pitchers & mugs',
    itemCount: 34,
  },
  {
    id: 'cat-home-decor',
    name: 'Home Decor',
    slug: 'home-decor',
    image: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=600&q=80',
    description: 'Minimalist ceramic vases, candle holders, mirrors & accent art',
    itemCount: 30,
  },
  {
    id: 'cat-kitchen',
    name: 'Kitchen',
    slug: 'kitchen',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
    description: 'Ceramic storage jars, oil dispensers, utensil holders & organizers',
    itemCount: 20,
  },
  {
    id: 'cat-gifting',
    name: 'Gifting',
    slug: 'gifting',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80',
    description: 'Curated gift hampers, festive boxes & celebratory sets',
    itemCount: 26,
  },
];

export const PRODUCTS: Product[] = [
  // 1. Ivory Bloom Dinner Set (Featured In Screenshot)
  {
    id: 'nest-dw-01',
    name: 'Ivory Bloom Dinner Set',
    subtitle: '(16 Pieces)',
    sku: 'DIN-IB-16P',
    soldCount: '25K+ sold',
    category: 'Dinnerware',
    subcategory: 'Dinner Sets',
    materialCategory: 'Ceramic',
    colorFamily: 'Beige',
    colorHex: '#EAE3D2',
    patternType: 'Floral',
    occasionType: 'Special Occasions',
    price: 3499,
    originalPrice: 4499,
    rating: 4.7,
    reviewsCount: 470,
    isNew: true,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=900&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Bring timeless elegance to your dining table with the Ivory Bloom Dinner Set. Crafted from high-quality ceramic, it features delicate floral patterns in soothing ivory tones – perfect for everyday meals and special occasions.',
    finish: 'Glossy',
    microwaveSafe: true,
    dishwasherSafe: true,
    chipResistant: true,
    features: ['Lead Free', 'Cadmium Free', 'Food Safe', 'Sustainable'],
    boxItems: [
      { name: 'Dinner Plate', size: '(10.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=400&q=80' },
      { name: 'Side Plate', size: '(7.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=400&q=80' },
      { name: 'Bowl', size: '(5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=400&q=80' },
      { name: 'Mug', size: '(300 ml)', count: 4, image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80' },
    ],
    details: {
      material: 'Premium Ceramic',
      dimensions: 'Dinner Plate: 10.5", Side Plate: 7.5", Bowl: 5", Mug: 300ml',
      volume: 'Mug: 300ml, Bowl: 450ml',
      care: 'Microwave & Dishwasher Safe, Gentle Hand Wash recommended for longevity',
      setIncludes: '4 Dinner Plates, 4 Side Plates, 4 Bowls, 4 Mugs (Total 16 Pieces)',
    },
    inStock: true,
    stockCount: 18,
    tags: ['Dinnerware', 'Dinner Sets', 'Ceramic', 'Floral', 'Special Occasions', 'Best Seller'],
  },

  // 2. Blue Jade Dinner Set (Featured In Screenshot)
  {
    id: 'nest-dw-rec-01',
    name: 'Blue Jade Dinner Set',
    subtitle: '(16 Pieces)',
    sku: 'DIN-BJ-16P',
    soldCount: '18K+ sold',
    category: 'Dinnerware',
    subcategory: 'Dinner Sets',
    materialCategory: 'Ceramic',
    colorFamily: 'Blue',
    colorHex: '#2B4C7E',
    patternType: 'Solid',
    occasionType: 'Special Occasions',
    price: 3599,
    originalPrice: 4599,
    rating: 4.8,
    reviewsCount: 352,
    isNew: true,
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Stunning deep blue jade glaze accented with gold-toned rim proportions. Brings regal sophistication to every gathering and family dinner.',
    finish: 'Glossy',
    microwaveSafe: true,
    dishwasherSafe: true,
    chipResistant: true,
    features: ['Lead Free', 'Cadmium Free', 'Food Safe', 'Sustainable'],
    boxItems: [
      { name: 'Dinner Plate', size: '(10.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=400&q=80' },
      { name: 'Side Plate', size: '(7.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=400&q=80' },
      { name: 'Bowl', size: '(5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=400&q=80' },
      { name: 'Mug', size: '(300 ml)', count: 4, image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80' },
    ],
    details: {
      material: 'High-fired Ceramic Porcelain',
      dimensions: 'Dinner Plate: 10.5", Side Plate: 7.5", Bowl: 5", Mug: 300ml',
      care: 'Microwave & Dishwasher Safe',
      setIncludes: '4 Dinner Plates, 4 Side Plates, 4 Bowls, 4 Mugs',
    },
    inStock: true,
    stockCount: 16,
    tags: ['Dinnerware', 'Dinner Sets', 'Ceramic', 'Blue', 'Floral'],
  },

  // 3. Pastel Petal Dinner Set (Screenshot recommendation 2)
  {
    id: 'nest-dw-02',
    name: 'Pastel Petal Dinner Set',
    subtitle: '(16 Pieces)',
    sku: 'DIN-PP-16P',
    soldCount: '15K+ sold',
    category: 'Dinnerware',
    subcategory: 'Dinner Sets',
    materialCategory: 'Ceramic',
    colorFamily: 'Pink',
    colorHex: '#EBBAB9',
    patternType: 'Floral',
    occasionType: 'Festive',
    price: 3299,
    originalPrice: 4199,
    rating: 4.9,
    reviewsCount: 305,
    isNew: false,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Delicate floral patterns with warm pastel pink tones. Designed to bring poetic grace and charm to every meal with family and guests.',
    finish: 'Glossy',
    microwaveSafe: true,
    dishwasherSafe: true,
    chipResistant: true,
    features: ['Lead Free', 'Cadmium Free', 'Food Safe', 'Sustainable'],
    boxItems: [
      { name: 'Dinner Plate', size: '(10.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=400&q=80' },
      { name: 'Side Plate', size: '(7.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=400&q=80' },
      { name: 'Bowl', size: '(5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=400&q=80' },
      { name: 'Mug', size: '(300 ml)', count: 4, image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80' },
    ],
    details: {
      material: 'High-fired Ceramic Earthenware',
      dimensions: 'Dinner Plate: 10.5", Side Plate: 7.5", Bowl: 5", Mug: 300ml',
      care: 'Microwave & Dishwasher Safe',
      setIncludes: '4 Dinner Plates, 4 Quarter Plates, 4 Katoris, 4 Cups',
    },
    inStock: true,
    stockCount: 22,
    tags: ['Dinnerware', 'Dinner Sets', 'Ceramic', 'Floral', 'Festive'],
  },

  // 4. Minimal White Dinner Set (Screenshot recommendation 3)
  {
    id: 'nest-dw-04',
    name: 'Minimal White Dinner Set',
    subtitle: '(16 Pieces)',
    sku: 'DIN-MW-16P',
    soldCount: '22K+ sold',
    category: 'Dinnerware',
    subcategory: 'Dinner Sets',
    materialCategory: 'Bone China',
    colorFamily: 'White',
    colorHex: '#F8F7F4',
    patternType: 'Solid',
    occasionType: 'Everyday Use',
    price: 2899,
    originalPrice: 3699,
    rating: 4.7,
    reviewsCount: 231,
    image: 'https://images.unsplash.com/photo-1526434426615-1abe81efcb0b?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1526434426615-1abe81efcb0b?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Timeless crisp white porcelain dinnerware set with ergonomic rim proportions and flawless glossy surface. The ultimate staple for modern homes.',
    finish: 'Glossy',
    microwaveSafe: true,
    dishwasherSafe: true,
    chipResistant: true,
    features: ['Lead Free', 'Cadmium Free', 'Food Safe', 'Sustainable'],
    boxItems: [
      { name: 'Dinner Plate', size: '(10.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1526434426615-1abe81efcb0b?auto=format&fit=crop&w=400&q=80' },
      { name: 'Side Plate', size: '(7.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=400&q=80' },
      { name: 'Bowl', size: '(5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=400&q=80' },
      { name: 'Mug', size: '(300 ml)', count: 4, image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80' },
    ],
    details: {
      material: 'Translucent Fine Bone China',
      dimensions: 'Dinner Plate: 10.5", Side Plate: 7.5", Bowl: 5", Mug: 300ml',
      care: 'Microwave, Oven and Dishwasher Safe',
      setIncludes: '4 Dinner Plates, 4 Side Plates, 4 Cereal Bowls, 4 Mugs',
    },
    inStock: true,
    stockCount: 30,
    tags: ['Dinnerware', 'Dinner Sets', 'Bone China', 'Solid', 'White', 'Everyday Use'],
  },

  // 5. Rustic Charm Dinner Set (Screenshot recommendation 4)
  {
    id: 'nest-dw-rec-02',
    name: 'Rustic Charm Dinner Set',
    subtitle: '(16 Pieces)',
    sku: 'DIN-RC-16P',
    soldCount: '12K+ sold',
    category: 'Dinnerware',
    subcategory: 'Dinner Sets',
    materialCategory: 'Stoneware',
    colorFamily: 'Tan',
    colorHex: '#C5A880',
    patternType: 'Vintage',
    occasionType: 'Everyday Use',
    price: 3199,
    originalPrice: 3999,
    rating: 4.8,
    reviewsCount: 214,
    image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Earthy textured stoneware with warm speckling and rustic hand-finished edges for cozy, hearty dining.',
    finish: 'Matte & Gloss Glaze',
    microwaveSafe: true,
    dishwasherSafe: true,
    chipResistant: true,
    features: ['Lead Free', 'Cadmium Free', 'Food Safe', 'Sustainable'],
    boxItems: [
      { name: 'Dinner Plate', size: '(10.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=400&q=80' },
      { name: 'Side Plate', size: '(7.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=400&q=80' },
      { name: 'Bowl', size: '(5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=400&q=80' },
      { name: 'Mug', size: '(300 ml)', count: 4, image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80' },
    ],
    details: {
      material: 'Natural Stoneware Ceramic',
      dimensions: 'Dinner Plate: 10.5", Side Plate: 7.5", Bowl: 5", Mug: 300ml',
      care: 'Dishwasher & Microwave Safe',
      setIncludes: '4 Dinner Plates, 4 Side Plates, 4 Bowls, 4 Mugs',
    },
    inStock: true,
    stockCount: 15,
    tags: ['Dinnerware', 'Dinner Sets', 'Stoneware', 'Vintage'],
  },

  // 6. Handpainted Heritage Set (Screenshot recommendation 5)
  {
    id: 'nest-dw-rec-03',
    name: 'Handpainted Heritage Set',
    subtitle: '(16 Pieces)',
    sku: 'DIN-HH-16P',
    soldCount: '9K+ sold',
    category: 'Dinnerware',
    subcategory: 'Dinner Sets',
    materialCategory: 'Ceramic',
    colorFamily: 'Beige',
    colorHex: '#D7C7B2',
    patternType: 'Floral',
    occasionType: 'Special Occasions',
    price: 3699,
    originalPrice: 4899,
    rating: 4.9,
    reviewsCount: 187,
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Traditional heritage brushwork crafted by master ceramicists, celebrating timeless floral motifs and heirloom craft quality.',
    finish: 'Glossy',
    microwaveSafe: true,
    dishwasherSafe: true,
    chipResistant: true,
    features: ['Lead Free', 'Cadmium Free', 'Food Safe', 'Sustainable'],
    boxItems: [
      { name: 'Dinner Plate', size: '(10.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=400&q=80' },
      { name: 'Side Plate', size: '(7.5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=400&q=80' },
      { name: 'Bowl', size: '(5 inch)', count: 4, image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=400&q=80' },
      { name: 'Mug', size: '(300 ml)', count: 4, image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80' },
    ],
    details: {
      material: 'Artisanal Glazed Ceramic',
      dimensions: 'Dinner Plate: 10.5", Side Plate: 7.5", Bowl: 5", Mug: 300ml',
      care: 'Dishwasher Safe, Microwave Safe',
      setIncludes: '4 Dinner Plates, 4 Side Plates, 4 Bowls, 4 Mugs',
    },
    inStock: true,
    stockCount: 19,
    tags: ['Dinnerware', 'Dinner Sets', 'Ceramic', 'Floral', 'Handpainted'],
  },

  // 7. Rustic Ceramic Bowl
  {
    id: 'nest-dw-05',
    name: 'Rustic Ceramic Bowl',
    subtitle: '(Set of 2)',
    category: 'Dinnerware',
    subcategory: 'Bowls',
    materialCategory: 'Ceramic',
    colorFamily: 'Tan',
    colorHex: '#D4A373',
    patternType: 'Solid',
    occasionType: 'Everyday Use',
    price: 499,
    originalPrice: 699,
    rating: 5,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Charming stoneware bowls with raw organic clay rim and warm oatmeal interior glaze. Ideal for curries, noodles, cereals, and ramen.',
    details: {
      material: 'Stoneware Ceramic with Earth Glaze',
      dimensions: 'Diameter: 15cm, Height: 7cm',
      volume: '650 ml each',
      care: 'Microwave and Dishwasher Safe',
      setIncludes: '2 Ceramic Bowls',
    },
    inStock: true,
    stockCount: 45,
    tags: ['Dinnerware', 'Bowls', 'Ceramic', 'Solid', 'Everyday Use'],
  },

  // 6. Handpainted Dinner Plate
  {
    id: 'nest-dw-06',
    name: 'Handpainted Dinner Plate',
    subtitle: '(Set of 2)',
    category: 'Dinnerware',
    subcategory: 'Dinner Plates',
    materialCategory: 'Ceramic',
    colorFamily: 'Beige',
    colorHex: '#E0D4C3',
    patternType: 'Floral',
    occasionType: 'Special Occasions',
    price: 699,
    originalPrice: 999,
    rating: 5,
    reviewsCount: 176,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Each plate is hand-brushed with vibrant botanical flora motifs by artisan craftspersons. A striking centerpiece for curated dinners.',
    details: {
      material: 'Artisan High-Fire Ceramic',
      dimensions: 'Diameter: 27cm',
      care: 'Dishwasher Safe, Microwave Safe',
      setIncludes: '2 Dinner Plates',
    },
    inStock: true,
    stockCount: 25,
    tags: ['Dinnerware', 'Dinner Plates', 'Ceramic', 'Floral', 'Special Occasions'],
  },

  // 7. Speckle Stoneware Bowl (Screenshot Recommendation 3)
  {
    id: 'nest-dw-07',
    name: 'Speckle Stoneware Bowl',
    subtitle: '(Set of 2)',
    category: 'Dinnerware',
    subcategory: 'Bowls',
    materialCategory: 'Stoneware',
    colorFamily: 'Beige',
    colorHex: '#D8CFBC',
    patternType: 'Geometric',
    occasionType: 'Everyday Use',
    price: 649,
    originalPrice: 849,
    rating: 5,
    reviewsCount: 123,
    image: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Nordic-inspired natural stoneware bowls featuring subtle dark mineral speckling and a raised lip border.',
    details: {
      material: 'Mineral Speckled Stoneware',
      dimensions: 'Diameter: 16cm, Height: 7cm',
      care: 'Dishwasher Safe & Microwave Safe',
      setIncludes: '2 Speckle Bowls',
    },
    inStock: true,
    stockCount: 38,
    tags: ['Dinnerware', 'Bowls', 'Stoneware', 'Geometric', 'Everyday Use'],
  },

  // 8. Floral Touch Side Plate
  {
    id: 'nest-dw-08',
    name: 'Floral Touch Side Plate',
    subtitle: '(Set of 4)',
    category: 'Dinnerware',
    subcategory: 'Side Plates',
    materialCategory: 'Porcelain',
    colorFamily: 'Pink',
    colorHex: '#F0C5C5',
    patternType: 'Floral',
    occasionType: 'Festive',
    price: 899,
    originalPrice: 1199,
    rating: 5,
    reviewsCount: 187,
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Charming quarter side plates tailored for desserts, salads, bread, or hors d’oeuvres with painted meadow wildflowers.',
    details: {
      material: 'Glazed Fine Porcelain',
      dimensions: 'Diameter: 20cm',
      care: 'Dishwasher & Microwave Safe',
      setIncludes: '4 Quarter Plates',
    },
    inStock: true,
    stockCount: 20,
    tags: ['Dinnerware', 'Side Plates', 'Porcelain', 'Floral', 'Festive'],
  },

  // 9. Pastel Ceramic Mug
  {
    id: 'nest-dw-09',
    name: 'Pastel Ceramic Mug',
    subtitle: '(Set of 2)',
    category: 'Dinnerware',
    subcategory: 'Mugs & Cups',
    materialCategory: 'Ceramic',
    colorFamily: 'Blue',
    colorHex: '#A3CEF1',
    patternType: 'Solid',
    occasionType: 'Everyday Use',
    price: 449,
    originalPrice: 599,
    rating: 5,
    reviewsCount: 215,
    image: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Cozy two-tone pastel ceramic coffee mugs with comfortable grip handle and satin smooth exterior.',
    details: {
      material: 'High-fire Ceramic',
      dimensions: 'Height: 10cm, Diameter: 8.5cm',
      volume: '340 ml each',
      care: 'Microwave Safe',
      setIncludes: '2 Pastel Mugs',
    },
    inStock: true,
    stockCount: 50,
    tags: ['Dinnerware', 'Mugs & Cups', 'Ceramic', 'Solid', 'Everyday Use'],
  },

  // 10. Ribbed Ceramic Bowl
  {
    id: 'nest-dw-10',
    name: 'Ribbed Ceramic Bowl',
    subtitle: '(Set of 2)',
    category: 'Dinnerware',
    subcategory: 'Bowls',
    materialCategory: 'Ceramic',
    colorFamily: 'Beige',
    colorHex: '#EAE0D5',
    patternType: 'Vintage',
    occasionType: 'Everyday Use',
    price: 549,
    originalPrice: 749,
    rating: 5,
    reviewsCount: 134,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Textured ribbed ridges on outer body with golden rim accents. Great for morning muesli, rice, or steaming broth.',
    details: {
      material: 'Ribbed Ceramic with Gold Luster Rim',
      dimensions: 'Diameter: 14cm, Height: 7.5cm',
      volume: '550 ml each',
      care: 'Dishwasher Safe',
      setIncludes: '2 Ribbed Bowls',
    },
    inStock: true,
    stockCount: 32,
    tags: ['Dinnerware', 'Bowls', 'Ceramic', 'Vintage', 'Everyday Use'],
  },

  // 11. Marble Glaze Dinner Plate
  {
    id: 'nest-dw-11',
    name: 'Marble Glaze Dinner Plate',
    subtitle: '(Set of 2)',
    category: 'Dinnerware',
    subcategory: 'Dinner Plates',
    materialCategory: 'Porcelain',
    colorFamily: 'White',
    colorHex: '#F0F0F0',
    patternType: 'Abstract',
    occasionType: 'Special Occasions',
    price: 699,
    originalPrice: 899,
    rating: 5,
    reviewsCount: 167,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Swirling grey and charcoal marble veins across pure white porcelain with a gleaming polished surface.',
    details: {
      material: 'Polished Glaze Porcelain',
      dimensions: 'Diameter: 27cm',
      care: 'Microwave and Dishwasher Safe',
      setIncludes: '2 Marble Plates',
    },
    inStock: true,
    stockCount: 28,
    tags: ['Dinnerware', 'Dinner Plates', 'Porcelain', 'Abstract', 'Special Occasions'],
  },

  // 12. Olive Grove Dinner Set
  {
    id: 'nest-dw-12',
    name: 'Olive Grove Dinner Set',
    subtitle: '(16 Pieces)',
    category: 'Dinnerware',
    subcategory: 'Dinner Sets',
    materialCategory: 'Stoneware',
    colorFamily: 'Green',
    colorHex: '#A3B18A',
    patternType: 'Vintage',
    occasionType: 'Special Occasions',
    price: 3499,
    originalPrice: 4599,
    rating: 5,
    reviewsCount: 312,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Earthy olive sage green tones with subtle rustic rim distressing. Brings Mediterranean sanctuary tranquility to your dinner table.',
    details: {
      material: 'Heavyweight Matte Stoneware',
      dimensions: 'Dinner Plate: 27cm, Side Plate: 20cm, Bowl: 15cm, Cup: 330ml',
      care: 'Dishwasher, Microwave & Oven Safe',
      setIncludes: '4 Plates, 4 Quarter Plates, 4 Bowls, 4 Cups',
    },
    inStock: true,
    stockCount: 16,
    tags: ['Dinnerware', 'Dinner Sets', 'Stoneware', 'Vintage', 'Special Occasions'],
  },

  // 13. Elegant Soup Bowl
  {
    id: 'nest-dw-13',
    name: 'Elegant Soup Bowl',
    subtitle: '(Set of 2)',
    category: 'Dinnerware',
    subcategory: 'Bowls',
    materialCategory: 'Bone China',
    colorFamily: 'Beige',
    colorHex: '#F5EBE0',
    patternType: 'Solid',
    occasionType: 'Special Occasions',
    price: 499,
    originalPrice: 699,
    rating: 5,
    reviewsCount: 98,
    image: 'https://images.unsplash.com/photo-1516715094483-75da7dee9758?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1516715094483-75da7dee9758?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Double-handled aristocratic soup and broth bowl with matching ceramic underplate saucer and gilded line border.',
    details: {
      material: 'Translucent Fine Bone China',
      dimensions: 'Diameter: 12cm, Width with handles: 17cm',
      volume: '380 ml each',
      care: 'Hand wash recommended',
      setIncludes: '2 Soup Bowls with Handles + 2 Saucers',
    },
    inStock: true,
    stockCount: 24,
    tags: ['Dinnerware', 'Bowls', 'Bone China', 'Solid', 'Special Occasions'],
  },

  // 14. Wave Serving Bowl
  {
    id: 'nest-dw-14',
    name: 'Wave Serving Bowl',
    subtitle: '(Medium)',
    category: 'Dinnerware',
    subcategory: 'Serving Bowls',
    materialCategory: 'Ceramic',
    colorFamily: 'Beige',
    colorHex: '#E6CCB2',
    patternType: 'Abstract',
    occasionType: 'Special Occasions',
    price: 799,
    originalPrice: 1099,
    rating: 5,
    reviewsCount: 122,
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Sculptural undulated wave rim with glossy cream reactive glaze. Stunning for serving tossed salads, pasta dishes, or fresh fruit.',
    details: {
      material: 'Sculptural Artisan Ceramic',
      dimensions: 'Diameter: 23cm, Height: 8cm',
      volume: '1400 ml',
      care: 'Dishwasher Safe',
      setIncludes: '1 Wave Serving Bowl',
    },
    inStock: true,
    stockCount: 19,
    tags: ['Dinnerware', 'Serving Bowls', 'Ceramic', 'Abstract', 'Special Occasions'],
  },

  // 15. Minimal White Platter (Screenshot Recommendation 5)
  {
    id: 'nest-dw-15',
    name: 'Minimal White Platter',
    subtitle: '(Large)',
    category: 'Dinnerware',
    subcategory: 'Platters & Trays',
    materialCategory: 'Porcelain',
    colorFamily: 'White',
    colorHex: '#FFFFFF',
    patternType: 'Solid',
    occasionType: 'Everyday Use',
    price: 899,
    originalPrice: 1199,
    rating: 5,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Generous oval ceramic serving platter designed for roasts, sushi rolls, antipasti, and appetizer spreads.',
    details: {
      material: 'Reinforced Hotel-grade Porcelain',
      dimensions: 'Length: 36cm, Width: 24cm',
      care: 'Dishwasher, Microwave & Oven Safe',
      setIncludes: '1 Oval Platter',
    },
    inStock: true,
    stockCount: 35,
    tags: ['Dinnerware', 'Platters & Trays', 'Porcelain', 'Solid', 'Everyday Use'],
  },

  // 16. Boho Bliss Dinner Set
  {
    id: 'nest-dw-16',
    name: 'Boho Bliss Dinner Set',
    subtitle: '(16 Pieces)',
    category: 'Dinnerware',
    subcategory: 'Dinner Sets',
    materialCategory: 'Stoneware',
    colorFamily: 'Tan',
    colorHex: '#DDA15E',
    patternType: 'Floral',
    occasionType: 'Festive',
    price: 3699,
    originalPrice: 4899,
    rating: 5,
    reviewsCount: 276,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'Rich bohemian earthy motifs in warm terracottas and ochre tones. Hand-stamped artisan craftsmanship for memorable dining experiences.',
    details: {
      material: 'Heavy Stoneware Ceramic',
      dimensions: 'Dinner Plate: 27cm, Side Plate: 20cm, Bowl: 15cm, Mug: 350ml',
      care: 'Dishwasher & Microwave Safe',
      setIncludes: '4 Dinner Plates, 4 Quarter Plates, 4 Bowls, 4 Mugs',
    },
    inStock: true,
    stockCount: 15,
    tags: ['Dinnerware', 'Dinner Sets', 'Stoneware', 'Floral', 'Festive'],
  },

  // Extra items for Dinnerware page 2 & other categories
  {
    id: 'nest-dw-17',
    name: 'Nordic Slate Coupe Plate',
    subtitle: '(Set of 4)',
    category: 'Dinnerware',
    subcategory: 'Dinner Plates',
    materialCategory: 'Stoneware',
    colorFamily: 'Black',
    colorHex: '#2B2D42',
    patternType: 'Solid',
    occasionType: 'Everyday Use',
    price: 1199,
    originalPrice: 1599,
    rating: 5,
    reviewsCount: 84,
    image: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80'],
    description: 'Matte charcoal black coupe dinner plates with modern minimalist Scandinavian curved silhouette.',
    details: { material: 'Matte Stoneware', dimensions: '26cm', care: 'Dishwasher Safe', setIncludes: '4 Plates' },
    inStock: true,
    stockCount: 20,
    tags: ['Dinnerware', 'Dinner Plates', 'Stoneware', 'Black', 'Solid'],
  },
  {
    id: 'nest-dw-18',
    name: 'Botanical Garden Serving Platter',
    subtitle: '(Large)',
    category: 'Dinnerware',
    subcategory: 'Platters & Trays',
    materialCategory: 'Porcelain',
    colorFamily: 'Green',
    colorHex: '#588157',
    patternType: 'Floral',
    occasionType: 'Festive',
    price: 999,
    originalPrice: 1299,
    rating: 5,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80'],
    description: 'Fine porcelain rectangular platter with intricate green fern and botanic foliage illustrations.',
    details: { material: 'Porcelain', dimensions: '34cm x 22cm', care: 'Dishwasher Safe', setIncludes: '1 Platter' },
    inStock: true,
    stockCount: 17,
    tags: ['Dinnerware', 'Platters & Trays', 'Porcelain', 'Floral', 'Festive'],
  },

  // Serveware
  {
    id: 'nest-sw-01',
    name: 'Handwoven Rattan Round Tray',
    subtitle: '(Medium)',
    category: 'Serveware',
    subcategory: 'Platters & Trays',
    materialCategory: 'Stoneware',
    colorFamily: 'Tan',
    colorHex: '#C59B27',
    patternType: 'Geometric',
    occasionType: 'Everyday Use',
    price: 899,
    originalPrice: 1199,
    rating: 5,
    reviewsCount: 64,
    isNew: true,
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80'],
    description: 'Braided sustainable rattan tray with reinforced handles for serving drinks and breakfast in bed.',
    details: { material: 'Natural Rattan', dimensions: '32cm Diameter', care: 'Wipe clean', setIncludes: '1 Tray' },
    inStock: true,
    stockCount: 15,
    tags: ['Serveware', 'Platters & Trays', 'Rattan', 'Tan'],
  },

  // Drinkware
  {
    id: 'nest-dr-01',
    name: 'Amber Ribbed Glass Tumblers',
    subtitle: '(Set of 6)',
    category: 'Drinkware',
    subcategory: 'Glassware',
    materialCategory: 'Glass',
    colorFamily: 'Tan',
    colorHex: '#DDA15E',
    patternType: 'Vintage',
    occasionType: 'Everyday Use',
    price: 1199,
    originalPrice: 1599,
    rating: 5,
    reviewsCount: 86,
    isNew: true,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80'],
    description: 'Amber fluted glassware with subtle vintage vertical fluting. Suitable for iced beverages and cocktails.',
    details: { material: 'Borosilicate Glass', dimensions: '14cm x 7cm', volume: '380ml each', care: 'Dishwasher Safe', setIncludes: '6 Tumblers' },
    inStock: true,
    stockCount: 34,
    tags: ['Drinkware', 'Glass', 'Tan', 'Vintage'],
  },

  // Home Decor
  {
    id: 'nest-hd-01',
    name: 'Sculptural Cream Ceramic Vase',
    subtitle: '(Medium)',
    category: 'Home Decor',
    subcategory: 'Vases',
    materialCategory: 'Ceramic',
    colorFamily: 'Beige',
    colorHex: '#FAF0CA',
    patternType: 'Abstract',
    occasionType: 'Everyday Use',
    price: 699,
    originalPrice: 899,
    rating: 5,
    reviewsCount: 92,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=800&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=800&q=80'],
    description: 'Matte unglazed textured ceramic vase with modern curved silhouette for pampas grass and botanical stems.',
    details: { material: 'Matte Ceramic', dimensions: '22cm x 11cm', care: 'Wipe clean', setIncludes: '1 Vase' },
    inStock: true,
    stockCount: 27,
    tags: ['Home Decor', 'Ceramic', 'Beige', 'Abstract'],
  },

  // Gifting
  {
    id: 'nest-gf-01',
    name: 'Royale Heritage Luxury Gift Hamper',
    subtitle: '(Gift Box)',
    category: 'Gifting',
    subcategory: 'Gift Sets',
    materialCategory: 'Ceramic',
    colorFamily: 'Tan',
    colorHex: '#D4A373',
    patternType: 'Floral',
    occasionType: 'Gifting',
    price: 2499,
    originalPrice: 3299,
    rating: 5,
    reviewsCount: 52,
    isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80'],
    description: 'Presented in Nestania’s signature rigid gold-embossed gift hamper box with silk ribbon. Includes 2 artisan hand-painted bowls, 2 matching brass dessert spoons, and a scented soy candle.',
    details: { material: 'Ceramic + Brass + Wax', dimensions: '35cm x 25cm x 12cm', care: 'Handle with care', setIncludes: '2 Bowls, 2 Spoons, 1 Candle, 1 Gift Box' },
    inStock: true,
    stockCount: 20,
    tags: ['Gifting', 'Gifting Made Special', 'Gift Sets', 'Festive'],
  }
];

export const COUPONS: Coupon[] = [
  {
    code: 'NEST10',
    discountPercent: 10,
    minOrder: 500,
    maxDiscount: 1000,
    description: 'Get 10% off on your order (Featured Welcome Code)',
  },
  {
    code: 'PREPAID10',
    discountPercent: 10,
    minOrder: 999,
    maxDiscount: 1500,
    description: 'Extra 10% Off on all Prepaid Orders',
  },
  {
    code: 'FESTIVE15',
    discountPercent: 15,
    minOrder: 2500,
    maxDiscount: 2000,
    description: '15% Off on orders above ₹2,499',
  },
  {
    code: 'LUXURY20',
    discountPercent: 20,
    minOrder: 4000,
    maxDiscount: 3000,
    description: '20% Off on luxury dining collections above ₹4,000',
  }
];

export const INSTAGRAM_POSTS = [
  {
    id: 'ig-1',
    image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=500&q=80',
    caption: 'Sunday table styling with our Ivory Bloom collection ✨ #NestaniaHome',
    likes: 1420,
  },
  {
    id: 'ig-2',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=500&q=80',
    caption: 'Golden hour moments with amber fluted glassware 🥂 #TableScape',
    likes: 980,
  },
  {
    id: 'ig-3',
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=500&q=80',
    caption: 'Cozy evenings by candlelight with fluted stoneware candle stands 🕯️',
    likes: 2150,
  },
  {
    id: 'ig-4',
    image: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=500&q=80',
    caption: 'Morning brew in the Floral Ceramic Mug 🌸 Slow mornings',
    likes: 1750,
  },
  {
    id: 'ig-5',
    image: 'https://images.unsplash.com/photo-1576020799627-aeac76d580dc?auto=format&fit=crop&w=500&q=80',
    caption: 'Artisan salads served in blush porcelain with 24k gold rim 🥗',
    likes: 1230,
  },
  {
    id: 'ig-6',
    image: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=500&q=80',
    caption: 'Minimal corners with dried florals and matte cream pottery 🌾',
    likes: 3100,
  },
];
